class MultiDiGraph:

    def __init__(self, node_data: dict, edge_data: dict):...
    def get(self, node: str):...
    def loop_get_item(self, number_access: int):...
    def loop_set_item(self, number_access: int):...
